Repository gifaldyazkaa/hoshiro, pull requests merged in 2024-01, with the labels that each got.

#13 fix(routes): remove /api from root path and use the original one
  README.md
  __test__/app.test.ts
  app.ts
  routes/index.ts
  routes/info/api.ts
  routes/info/notfound.ts
  routes/info/root.ts
Labels: enhancement, breaking

#15 fix(rename): project name rebranding
  LICENSE
  README.md
  package.json
Labels: documentation, help wanted

#17 feat(cd): setup action for build and deploy
  .github/workflows/build.yaml
  Dockerfile
  package.json
Labels: enhancement
